
þ
root"_tf_keras_model*Þ
{"name": "HousePriceCusomModel", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "HousePriceCusomModel", "config": {}, "shared_object_id": 0, "build_input_shape": {"class_name": "__tuple__", "items": [{"class_name": "TensorShape", "items": [32, 32, 32, 12]}, {"class_name": "TensorShape", "items": [32, 4]}]}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [32, 32, 32, 12]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [32, 4]}, "float32", "input_2"]}]}], {}]}, "save_spec": {"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [32, 32, 32, 12]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [32, 4]}, "float32", "input_2"]}]}, "keras_version": "2.10.0", "backend": "tensorflow", "model_config": {"class_name": "HousePriceCusomModel", "config": {}}}2
íroot.image_encoder"_tf_keras_layer*½{"name": "ImageEncoder", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "ImageEncoder", "config": {"name": "ImageEncoder", "trainable": true, "dtype": "float32"}, "shared_object_id": 1, "build_input_shape": {"class_name": "TensorShape", "items": [32, 32, 32, 12]}}2
ì	root.tabular_encoder"_tf_keras_layer*º{"name": "TabularEncoder", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "TabularEncoder", "config": {"name": "TabularEncoder", "trainable": true, "dtype": "float32"}, "shared_object_id": 2, "build_input_shape": {"class_name": "TensorShape", "items": [32, 4]}}2
Ÿ
root.concat"_tf_keras_layer*ö{"name": "CustomConcat", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomConcat", "config": {"name": "CustomConcat", "trainable": true, "dtype": "float32", "axis": -1}, "shared_object_id": 3, "build_input_shape": [{"class_name": "TensorShape", "items": [32, 128]}, {"class_name": "TensorShape", "items": [32, 64]}]}2
æroot.fc1"_tf_keras_layer*À{"name": "CustomDense", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomDense", "config": {"name": "CustomDense", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 4, "build_input_shape": {"class_name": "TensorShape", "items": [32, 192]}}2
Ö	root.relu"_tf_keras_layer*¯{"name": "CustomRelu", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomRelu", "config": {"name": "CustomRelu", "trainable": true, "dtype": "float32"}, "shared_object_id": 5, "build_input_shape": {"class_name": "TensorShape", "items": [32, 64]}}2
äroot.fc2"_tf_keras_layer*¾{"name": "CustomDense", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomDense", "config": {"name": "CustomDense", "trainable": true, "dtype": "float32", "units": 1}, "shared_object_id": 6, "build_input_shape": {"class_name": "TensorShape", "items": [32, 64]}}2
‹,root.image_encoder.conv1"_tf_keras_layer*Õ{"name": "CustomConv2D", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomConv2D", "config": {"name": "CustomConv2D", "trainable": true, "dtype": "float32", "filters": 32, "kernel_size": {"class_name": "__tuple__", "items": [3, 3]}, "strides": {"class_name": "__tuple__", "items": [1, 1]}, "padding": "SAME"}, "shared_object_id": 7, "build_input_shape": {"class_name": "TensorShape", "items": [32, 32, 32, 12]}}2
í-root.image_encoder.relu1"_tf_keras_layer*·{"name": "CustomRelu", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomRelu", "config": {"name": "CustomRelu", "trainable": true, "dtype": "float32"}, "shared_object_id": 8, "build_input_shape": {"class_name": "TensorShape", "items": [32, 32, 32, 32]}}2
‹.root.image_encoder.conv2"_tf_keras_layer*Õ{"name": "CustomConv2D", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomConv2D", "config": {"name": "CustomConv2D", "trainable": true, "dtype": "float32", "filters": 64, "kernel_size": {"class_name": "__tuple__", "items": [3, 3]}, "strides": {"class_name": "__tuple__", "items": [1, 1]}, "padding": "SAME"}, "shared_object_id": 9, "build_input_shape": {"class_name": "TensorShape", "items": [32, 32, 32, 32]}}2
î/root.image_encoder.relu2"_tf_keras_layer*¸{"name": "CustomRelu", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomRelu", "config": {"name": "CustomRelu", "trainable": true, "dtype": "float32"}, "shared_object_id": 10, "build_input_shape": {"class_name": "TensorShape", "items": [32, 32, 32, 64]}}2
ù0root.image_encoder.flatten"_tf_keras_layer*Á{"name": "CustomFlatten", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomFlatten", "config": {"name": "CustomFlatten", "trainable": true, "dtype": "float32"}, "shared_object_id": 11, "build_input_shape": {"class_name": "TensorShape", "items": [32, 32, 32, 64]}}2
÷1root.image_encoder.fc"_tf_keras_layer*Ä{"name": "CustomDense", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomDense", "config": {"name": "CustomDense", "trainable": true, "dtype": "float32", "units": 128}, "shared_object_id": 12, "build_input_shape": {"class_name": "TensorShape", "items": [32, 65536]}}2
õ8root.tabular_encoder.fc1"_tf_keras_layer*¿{"name": "CustomDense", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomDense", "config": {"name": "CustomDense", "trainable": true, "dtype": "float32", "units": 32}, "shared_object_id": 13, "build_input_shape": {"class_name": "TensorShape", "items": [32, 4]}}2
è9root.tabular_encoder.relu1"_tf_keras_layer*°{"name": "CustomRelu", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomRelu", "config": {"name": "CustomRelu", "trainable": true, "dtype": "float32"}, "shared_object_id": 14, "build_input_shape": {"class_name": "TensorShape", "items": [32, 32]}}2
ö:root.tabular_encoder.fc2"_tf_keras_layer*À{"name": "CustomDense", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomDense", "config": {"name": "CustomDense", "trainable": true, "dtype": "float32", "units": 64}, "shared_object_id": 15, "build_input_shape": {"class_name": "TensorShape", "items": [32, 32]}}2
è;root.tabular_encoder.relu2"_tf_keras_layer*°{"name": "CustomRelu", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "CustomRelu", "config": {"name": "CustomRelu", "trainable": true, "dtype": "float32"}, "shared_object_id": 16, "build_input_shape": {"class_name": "TensorShape", "items": [32, 64]}}2